version: '3'
services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
      POSTGRES_INITDB_ARGS: '-E utf-8'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5432:5432'
volumes:
  dbdata: null
